// ============================================================
// FILE: src/app/services/layout.js
// This adds SEO metadata specifically for the /services page
// ============================================================

export const metadata = {
  title: "Buy Final Year Projects, Mini Projects, Conference & Journal Papers | Journify Technologies",
  description: "Buy final year project implementation, mini project, conference paper writing, journal paper writing, IEEE paper, Scopus paper, plagiarism removal for engineering students in India. Trusted by 500+ students across Tamil Nadu, Chennai, Coimbatore. WhatsApp: 7904203916",
  keywords: [
    "buy final year project", "final year project buying", "final year project implementation",
    "final year project implementation service", "final year project implementation india",
    "final year project implementation tamil nadu", "final year project implementation chennai",
    "final year project implementation coimbatore", "final year project for engineering students",
    "engineering final year project buying", "engineering final year project implementation",
    "final year project buying india", "final year project service india",
    "final year project help india", "final year project assistance india",
    "final year project developers india", "best final year project service",
    "final year project with source code", "final year project with documentation",
    "final year project with report", "final year project with ppt",
    "buy final year project online", "buy final year project india",
    "buy final year project chennai", "buy final year project coimbatore",
    "final year project for btech", "final year project for be",
    "final year project for mtech", "final year project for mca",
    "buy mini project", "mini project buying", "mini project implementation",
    "mini project implementation india", "mini project implementation service",
    "mini project for engineering students", "mini project buying india",
    "mini project buying online", "buy mini project online",
    "mini project with source code", "mini project developers india",
    "mini project implementation chennai", "mini project implementation coimbatore",
    "3rd year mini project india", "semester project buying",
    "buy conference paper", "conference paper buying", "conference paper writing service",
    "conference paper writing india", "conference paper writing for engineering students",
    "IEEE paper writing service", "IEEE paper writing india",
    "IEEE conference paper buying", "buy IEEE conference paper",
    "Springer paper writing service", "conference paper writing service india",
    "buy conference paper india", "conference paper writing tamil nadu",
    "conference paper writing chennai", "conference paper writing coimbatore",
    "conference paper for final year project", "conference paper publication india",
    "buy journal paper", "journal paper buying", "journal paper writing service",
    "journal paper writing india", "Scopus paper writing", "SCI paper writing",
    "Scopus indexed journal paper india", "buy Scopus paper",
    "journal paper for engineering students", "journal paper for final year",
    "journal paper buying india", "journal paper writing tamil nadu",
    "journal paper writing chennai", "journal paper writing coimbatore",
    "Scopus journal paper service", "SCI journal paper service india",
    "buy research paper india", "research paper writing service india",
    "research paper writing for students", "journal publication service india",
    "project implementation buying", "project implementation service india",
    "buy project implementation", "implementation buying india",
    "project implementation for engineering", "buy implementation project",
    "implementation service india", "project implementation service chennai",
    "machine learning project buying", "deep learning project buying",
    "AI project implementation india", "artificial intelligence project buying",
    "IoT project implementation", "IoT project buying india",
    "web development project buying", "android project buying",
    "blockchain project buying", "cloud computing project buying",
    "cybersecurity project buying", "data science project buying",
    "python project buying", "java project buying",
    "plagiarism removal service india", "plagiarism removal india",
    "plagiarism removal for students", "turnitin safe content india",
    "AI content humanizing india", "plagiarism removal chennai",
    "ppt presentation buying", "buy ppt presentation india",
    "academic service india", "academic service tamil nadu",
    "academic service chennai", "academic service coimbatore",
    "student project service india", "engineering student project help",
    "journify technologies", "journify project service",
    "trusted project service india", "affordable project service india",
    "best project service india", "top project service india",
    "anna university project", "vit project", "srm project", "psg tech project",
  ],
  openGraph: {
    title: "Buy Final Year Projects & Research Papers | Journify Technologies",
    description: "Trusted academic service for engineering students. Buy final year project, mini project, conference paper, journal paper, IEEE paper in India.",
    url: "https://journify.tech/services",
    images: [{ url: "/og-image.jpeg", width: 1200, height: 630 }],
  },
  alternates: {
    canonical: "https://journify.tech/services",
  },
};

export default function ServicesLayout({ children }) {
  return <>{children}</>;
}